M48
; DRILL file {KiCad 7.0.10} date Saturday, February 01, 2025 at 12:29:47 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-02-01T12:29:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X131.064Y-97.282
X149.86Y-83.82
X149.86Y-110.998
M30
